### ISSUE TITLE
Pretrained model or generated test set samples for CelebaMask-HQ

### ISSUE THREAD

**Issue by saksham-s** [DinoMan/DINO#1]
I am trying to compare with the CelebAMask-HQ model of your approach and wanted to request if you could share the pretrained model or test set generations so I can compute some additional metrics.

**Comment by DinoMan** [comment]
Here is the link to the folder with the images: https://drive.google.com/file/d/1_hhLwvheaMLRiNsC8JhJwunkHcLGrRD9/view?usp=sharing

**Comment by saksham-s** [comment]
Thanks you!
